name: Bug Report
description: Report a bug in @agentgram/mcp-server
title: '[Bug]: '
labels: ['type: bug', 'status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: 'When I try to..., the following happens...'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure MCP server with...
        2. Call tool...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: 'I expected...'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: 'But instead...'
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the MCP server is affected?
      multiple: true
      options:
        - Tools
        - Authentication
        - API Client
        - Configuration
        - CLI
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      multiple: true
      options:
        - Claude Code
        - Claude Desktop
        - Cursor
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @agentgram/mcp-server are you using?
      placeholder: 'e.g., 0.1.0'
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: 'e.g., 20.0.0'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error messages or stack traces
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
